#!/usr/bin/env python3

import runpy
from pathlib import Path

here = Path(__file__).parent
manager = runpy.run_path(str(Path(__file__).parent / "bootstrap_venvstarter.py"))["manager"]

manager = manager(None).named(".python")

manager.add_local_dep(
    "{here}",
    "..",
    version_file=("my_library", "version.py"),
    name="my_library=={version}",
)

manager.add_requirements_file("{here}", "requirements.dev.txt")

manager.min_python("3.11")
manager.run()
